favicon: /favicon.png
#UA-114426812-1
google_analytics:

staticman: Soren234/hexo-sorentryde-blog/
comment_history: true
comment_enable: true
recent_comment: 0
comment_reply: false

reCaptcha:
  enabled: true
  siteKey: "6LcnQEwUAAAAAG4biRYcrrF0WboQEQcr19bkqNiJ"
  secret: "EIt+QN/zY1TjNwMckD4rHl/bM8mVsWQN/JHJ1Ze+kKn0h3HLceqTITlqEMVDgWjPob1Xqfk95ANKc9EAJMCYF7UeFbJsV0U96SMAf7FhwRhow3yfVFxOxHiZgvlEFSKETVh3Fu7zEHxyQJ9R8Mhht7K0LD1fs7v4nt0dp9iHRCv+MI9N/efphpXK1qaJ0w5yCGzJ1cuYK/PdBkZaEgODhhJY1PwplcNOi5mEej32ldT3iKaSFo/2OBWdAstnZN3XVjiyhtRE30pkwQNqlytoLGAsq53F0arISB2XkMjCwmkNkUxHZtTAj+Rd5wp0mF7p9cuiFXvgL4f2Q8tRt/D/Ww=="