favicon: /favicon.png
#UA-114426812-1
google_analytics:

staticman: Soren234/hexo-sorentryde-blog/
comment_history: true
comment_enable: true
recent_comment: 0
comment_reply: false

reCaptcha:
  enabled: true
  siteKey: "6Lc1mMwUAAAAAMZBwCERrlakRdXSRCFQSU8vj-Bh"
  secret: "kwMRKgC6dPYpi+FI0bdVK8rjIafCDrFT5QWwEFuZdZGp+/M3P2TQr3q4MkK+gt08AGRNBGIFdPZI6eqwJPca6oayOu9/xTdA9EAG9Buu2F2YfAWwSRsULIlcuFQXcY7yCgKhKpjkAefpR6wb6u0GWHNEAKzeg7K7mUDDb9z6Ydu6loAUokBPbAnkGNY1mQ5EzpVQauCN+cXl6lhl0wfbzEM7gN3HoBTIMR/yvfLLnnqLUzTOQYG0D11mEBQJSvRQqx6ZI5diD5R+H8iMpe+UkPa7vFBCPzkJ67hpkdGZVxW1fe9Tc4P8OBg5rB7gUO1v0q5p7gGVtWLVb5m0wHcGvw=="